### ISSUE TITLE
Coding rules

### ISSUE THREAD

**Issue by mermetbt** [OragonEfreet/renderer#2]
https://github.com/OragonEfreet/renderer/blob/839ad86a6caa4b48444153c2069fe1d4c7826897/linmath.h#L14

It's lacking comments everywhere!

**Comment by OragonEfreet** [comment]
Yes ! I care about the planet! I process less bytes this way! :earth_africa: 
:trollface:

**Comment by OragonEfreet** [comment]
@mermetbt Comments are provided through inline documentation generating [this website](https://oragonefreet.github.io/banjo/framebuffer_8h.html#a4d198c7e9d3e1b49bbac9072888f4344) on the canonical project. This project is a draft. Also coucou ça va, la femme les enfants le chien ?
